export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILURE = 'UPDATE_USER_PASSWORD_FAILURE';
export const UPDATE_USER_PASSWORD_INIT = 'UPDATE_USER_PASSWORD_INIT';

export const INITIAL_STATE = {
  loading: false,
  loaded: false,
  error: '',
};
