export const LOAD_ORGANIZATIONS_REQUEST = 'LOAD_ORGANIZATIONS_REQUEST';
export const LOAD_ORGANIZATIONS_SUCCESS = 'LOAD_ORGANIZATIONS_SUCCESS';
export const LOAD_ORGANIZATIONS_FAILURE = 'LOAD_ORGANIZATIONS_FAILURE';
